mathvista:
  local_dir: data/MathVista
  hf_path: AI4Math/MathVista
  
mmmath:
  local_dir: data/MM_Math
  hf_path: THU-KEG/MM_Math

MMMU:
  local_dir:
  hf_path: MMMU/MMMU
  subset: ['Accounting', 'Agriculture', 'Architecture_and_Engineering', 'Art', 'Art_Theory', 'Basic_Medical_Science', 'Biology', 'Chemistry', 'Clinical_Medicine', 'Computer_Science', 'Design', 'Diagnostics_and_Laboratory_Medicine', 'Economics', 'Electronics', 'Energy_and_Power', 'Finance', 'Geography', 'History', 'Literature', 'Manage', 'Marketing', 'Materials', 'Math', 'Mechanical_Engineering', 'Music', 'Pharmacy', 'Physics', 'Psychology', 'Public_Health', 'Sociology']

  