vllm:
  host: "localhost"
  port: 7788
  trust_remote_code: true 
  api_key: api-lyt-78fd9
  
openai:
  api_key: sk-viE4vGraznKsTmxP458b38306e9b42F4863aCb1aD63a72F1
  api_base_url: https://api.lmtchina.com/v1
