r1_think_prompt:
  system: "You are a good AI asisstent, help me to solve the questions."
  user: |
    {query}
    You FIRST think about the reasoning process as an internal monologue and then provide the final answer.
    The reasoning process MUST BE enclosed within <think> </think> tags. The final answer MUST BE put in \boxed{{}}.
